[package]
name = "crypto"
description = """
Cryptography primitives used for validating binaries.
This is shared between the bootloader, kernel, and more.
"""
version = "0.1.0"
edition = "2021"
license = "MIT AND Apache-2.0"

[dependencies]
